# Project info
site_name: IBM Cloud Object Storage Level 3 Demonstration Guide
site_description: IBM Cloud Object Storage Level 3 Demonstration Guide
site_author: Andrew R. Jones (andrewj@us.ibm.com)
copyright: Copyright &copy; 2022 IBM

# Repository
repo_name: IBM/SalesEnablement-COS-L3
#repo_url: https://github.com/IBM/SalesEnablement-PowerVS-L3
#edit_uri: edit/master/docs
docs_dir: docs


nav:
  - Introduction: 'index.md'
  - Part 1 - Overview:
    - 'Introduction': 'Part 1/01 Introduction.md'
  - Part 2 - Provisioning a COS service:
    - 'Introduction': 'Part 2/01 Introduction.md'
  - Part 3 - Next steps:
    - 'Next steps': 'Part 3/01 Introduction.md'

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
    - mkdocs-video
    - macros
    - search

markdown_extensions:
  - sane_lists
  - pymdownx.details
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list

extra:
  generator: false
  learningplan:
    name: "IBM Cloud Object Storage - Level 3"
  slack:
    url: "https://ibm-technology-sales.slack.com/archives/C03PQ47KRQE"
  offering:
    name: "IBM Cloud Object Storage"
  guide:
    name: "IBM Cloud Object Storage- Level 3 Demonstration Guide"
    url: "https://ibm.github.io/SalesEnablement-COS-L3/"
  tz_environment:
    name: "IBM Cloud Object Storage - Sales Enablment L3"
    url: "https://techzone.ibm.com/my/reservations"
#  account: "2435442 - ITZ - Satellite"
  account: "2305900 - ITZ - ADHOC03"
  COS:
    serviceInstanceName: "COS-L3-service"
    serviceInstanceRG: "COS-L3"
    serviceInstanceLocation: "Dallas"
    serviceInstanceRegion: "us-south"
    bucket-1: "cos-l3-bucket-1"
    bucket-1-storageClass: "Smart Tier"
    bucket-1-minimumExpiry: "0"
    bucket-1-maximumExpiry: "2"

  KeyProtect:
    serviceInstanceName: "COS-L3-KP-service"
    serviceInstanceRG: "COS-L3"
    serviceInstanceLocation: "Dallas"
    serviceInstanceRegion: "us-south"
    rootKey: "COS-L3-RootKey-1"
