# Project info
site_name: IBM Cloud Object Storage Level 3 Demonstration Guide
site_description: IBM Cloud Object Storage Level 3 Demonstration Guide
site_author: Andrew R. Jones (andrewj@us.ibm.com)
copyright: Copyright &copy; 2022 IBM

# Repository
repo_name: IBM/SalesEnablement-COS-L3
#repo_url: https://github.com/IBM/SalesEnablement-PowerVS-L3
#edit_uri: edit/master/docs
docs_dir: docs


nav:
  - Introduction: 'index.md'
  - Part 1 - Overview of IBM Cloud Object Storage:
    - 'Introduction': 'Part 1/01 Introduction.md'
  - Part 2 - Create a COS service:
    - 'Introduction': 'Part 2/01 Introduction.md'
    - 'Watch a COS service being created': 'Part 2/02 Watch.md'
    - 'Click through demonstration of a COS service being created': 'Part 2/03 ClickThru.md'
  - Part 3 - Create a Key Protect service and root key:
    - 'Introduction': 'Part 3/01 Introduction.md'
    - 'Watch a Key Protect service and root key being created': 'Part 3/02 Watch.md'
    - 'Click through demonstration of a Key Protect service and root key being created': 'Part 3/03 ClickThru.md'
  - Part 4 - Create a Activity Tracker service:
    - 'Introduction': 'Part 4/01 Introduction.md'
    - 'Watch an Activity Tracker service being created': 'Part 4/02 Watch.md'
    - 'Click through demonstration of an Activity Tracker service being created': 'Part 4/03 ClickThru.md'
  - Part 5 - Create an service authorization:
    - 'Introduction': 'Part 5/01 Introduction.md'
    - 'Watch a service authorization being created': 'Part 5/02 Watch.md'
    - 'Click through demonstration of a service authorization being created': 'Part 5/03 ClickThru.md'
  - Part 6 - Create a COS bucket:
    - 'Introduction': 'Part 6/01 Introduction.md'
    - 'Watch a COS bucket being created': 'Part 6/02 Watch.md'
    - 'Click through demonstration of a COS bucket being created': 'Part 6/03 ClickThru.md'
  - Part 7 - Create COS objects:
    - 'Introduction': 'Part 7/01 Introduction.md'
    - 'Manage regulated content': 'Part 7/02 Manage regulated content.md'
    - 'Legal holds': 'Part 7/03 Legal holds.md'
  - Part 8 - Using COS Command Line Interfaces:
    - 'Introduction': 'Part 8/01 Introduction.md'
    - 'Manage regulated content': 'Part 8/02 Manage regulated content with COS CLIs.md'
  - Part 9 - Understanding COS Identifity and Access Management:
    - 'Introduction': 'Part 9/01 Introduction.md'
  - Next steps: 'NextSteps.md'


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
    - mkdocs-video
    - macros
    - search

markdown_extensions:
  - sane_lists
  - pymdownx.details
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list

extra:
  generator: false
  learningplan:
    name: "IBM Cloud Object Storage - Level 3"
  slack:
    url: "https://ibm-technology-sales.slack.com/archives/C03PQ47KRQE"
  offering:
    name: "IBM Cloud Object Storage"
  guide:
    name: "IBM Cloud Object Storage- Level 3 Demonstration Guide"
    url: "https://ibm.github.io/SalesEnablement-COS-L3/"
  tz_environment:
    name: "IBM Cloud Object Storage - Sales Enablment L3"
    url: "https://techzone.ibm.com/my/reservations"
#  account: "2435442 - ITZ - Satellite"
  account: "2305900 - ITZ - ADHOC03"
  COS:
    serviceInstanceName: "COS-L3-service"
    serviceInstanceID: "7ae313ac-9571-4bf6-bc55-aea286699a31"
    serviceInstanceRG: "COS-L3"
    serviceInstanceLocation: "Dallas"
    serviceInstanceRegion: "us-south"
    serviceEndpoint: "s3.us-south.cloud-object-storage.appdomain.cloud"
    bucket-1: "cos-l3-retain-policy"
    bucket-1-storageClass: "Smart Tier"
    bucket-1-retentionPolicy: true
    bucket-1-minimumExpiry: "0"
    bucket-1-maximumExpiry: "3"
    bucket-2: "cos-l3-no-retain-policy"
    bucket-2-storageClass: "Smart Tier"
    bucket-2-retentionPolicy: false

  ActivityTracker:
    serviceLocation: "Dallas (us-south)"
    servicePricingPlan: "7 day Event Search"
    serviceInstanceName: "COS-L3-activity-tracker"
    serviceInstanceRG: "COS-L3"

  KeyProtect:
    serviceInstanceName: "COS-L3-KP-service"
    serviceInstanceRG: "COS-L3"
    serviceInstanceLocation: "Dallas (us-south)"
    rootKey: "COS-L3-RootKey-1"
